language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Nh1ZagYZxum4Hc+AP/pORs7eSnBYQ4Bj1FzuSZwwwYY7QSvKGfm72Jm+4CIT/TgjWegxIPAlMgC1LHoIQBlHKJA4qe5apFLEwrM+wQhEYt0cJealMCKyH7wvQTWFXDTJeIaJWs1SquPOHPhGISX1konrwYGNgM/3SjVGSx7uiI7WaR5s4noGQvllSpCKEawVaWGJ5e3DXcz5Sw/KXAr5/Iwf+uv01sqjJWHZXWqpl8VfsvyIiE0FggLoZUlvtkkzDBBPHTiPeMzgbQNAwjmEi7nNbww88s+lpV/iEpIC8XXNoywzWvQ2hfrFFOcjUGglAMwplqFmVTcS4LpSEKiPth+yWKA5LFbIsxrzYiaWaOGV6HXrH7GP0EgjS++ZVJ21tV2F2mPEfNVGyMiCsnQSopS/Lbo7aF6LiFo05lv2XiNQSz3X4RZOlFfq/NCgR1upLhICrBlGNEiE7CEa8VEMYjKw9PpZtaXz9OoYqY7u9uoaXlG9l1lbRkr7LEhy4+A71G7D+gbkdW7Sx0lZy44vH90e1O3jlNhEi0TjnMsT2/WCEXHHxZdBQFrRjokV9xU5gHFOH3ZE+dHpdP7aXvRUyM+hMO5Ujn6BYfAmv98aZtcFGFya5r6cT2/WJS94eT0ww2w4hp/JvnqbNu47sh7OSJtFnv1fEzS7dXl6kUsfnOw=
  app: floating-brushlands-48834
  on:
    repo: rosaxny/node-restaurants-app-mongoose
    branch: feature/with-tests
