language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: gz64D+pLewTihDslEfK66eXCy+PjDqKbRdu3sd8+2D2D5N7QIo3ha1tXSwp4fQzYXYGqGi/LnSwOFB/7qzLQc3YGlRNvCk7CGf8APmIVDoEr2kuK3JhUFNdP1ab4O86H+c5bI1wvUop7M8IPKZi7+gDlvEHtRsBTeZaCdOaqASKFo9c61Zq7DyC5zY3u3uYxWGFDKpLGMhd9P5/Xv4RQvqPzJczM1A3biOSrWJgJd5YV5Uq+yy1YTsjqXDQYPTLuDlMRwVns2OmkvmdD0+m0Bq+DQnmMaRf+JJDahLtPOcN4MDQY+z+2JgPFX9jfDRZVZt0zUEICjyAq9gKoECFpVxjJlq0S18zZy9lEOGOhuNQCF82vI4HvEOJWvYVv3uW66+vH06VsB4y/2s28ZghS5JEMlnZaVWaaiYgnq4pV5HSrMI4kVFkO0dSRkL3eRnadMGJokhvZdvsKK2mO8tb9zGSwvF1V0qISDxOP07kFApaullcGD6lv0t482cpO00JvNJpjVktAlD+jluJy61qrMp937c0gr+Bz0mxEA9z+xsFgIFLL4Nv/yrBIlCxumddRURA/v97iVBxl5+h8SE6kDevfTg3qcdHa/+rf1SZ9SUUtI8toIEpwxMLmOPNBh0+njJtUkHVn4FUVLTRZFHPErZPzGuREnUl1Y0Siq46lkBQ=
  app: floating-brushlands-48834
  on:
    repo: rosaxny/node-restaurants-app-mongoose
    branch: feature/with-tests
